@base_url = http://localhost:3000

POST {{base_url}}/enviar-correo
Content-Type: application/json

{
  "para": "gissellgonzalez209@gmail.com",
  "asunto": "Que pasa mami",
  "mensaje": "Soy yo, tu papi, como esta la marea?"
}
